function u = ctrl(x,p,m_base,m_link,l,r)
%CTRL Chains the various controllers to compute the control action.

u = [max(min(angle_lqri(x, m_base,m_link,l, r,...
                          pos_pd(x, p(1)) ...
                             )...
                + height_lqri(x, m_base+4*m_link, p(2)),...
                [5;5]),...
               0);    % Bi-Rotor Inputs
               [0;5]... Tendon Inputs
            ];


end

