function u = ctrl(x,p,m_base,r)
%CTRL Chains the various controllers to compute the control action.

u = [max(min(angle_lqr(x, m_base, r,...
                          pos_pd(x, p(1)) ...
                             )...
                + height_lqri(x, m_base, r, 0),...
                [5;5]),...
               0);    % Bi-Rotor Inputs
               [0;5]... Tendon Inputs
            ];


end

